Lesson5
Lana-243/test-guru pull request #4
Opened 2022-01-18 19:29 UTC by Lana-243

2022-01-19 07:29 UTC, VidgarVii requested changes

2022-01-19 07:29 UTC, VidgarVii commented on app/models/category.rb
> +  has_many :tests
если категорию удалить, то в текущем варианте можно в дальнейшем получить ошибку

к примеру при попытке обратиться по ассоциации (`@test.category`)
или при каких-то операциях, которые подразумевают валидацию объекта

после удаления категории в таблице `tests` останется в поле `category_id` ссылка на несуществующий объект
т.е. объекты в таблице `tests` станут невалидными: рельсы по умолчанию проверяют наличие ассоциированного объекта для всех `belongs_to` ассоциаций (при валидации этого объекта) и выбрасывают ошибку валидации, если объекта не существует

если же на уровне бд поле `category_id` обозначено, как внешний ключ, то уже на попытке удаления объекта из таблицы `categories` получим ошибку базы данных, такого примерно вида:
```
ActiveRecord::InvalidForeignKey (PG::ForeignKeyViolation: EROR:  update or delete on table "categories" violates foreign key constraint
```
и рельсы откажутся удалять категорию

поэтому для всех `has_*` ассоциаций следует указывать поведение при удалении - можно посмотреть в документации - опция `dependent: ...`

2022-01-19 07:29 UTC, VidgarVii commented on app/models/question.rb
> +  has_many :answers
belongs_to и has_many разделяют пустыми строками. Такое разделение кода на логические блоки.
Пример оформления модели можно посмотреть тут https://github.com/rubocop/rails-style-guide#macro-style-methods

2022-01-19 07:29 UTC, VidgarVii commented on app/models/test.rb
> +  has_many :questions
Соблюдай очередность.
Принято сначала писать belongs_to далее ниже has_

2022-01-19 07:29 UTC, VidgarVii commented on app/models/test.rb
> +  belongs_to :user
1 не работает
2 тест принадлежит автору. Это надо явно указывать не только на уровне бд. но и в моделях. Эту темы уже проходили

2022-01-19 07:29 UTC, VidgarVii commented on app/models/test.rb
>      .where(categories: { title: category_title })
благодаря ассоциациям методы можно сильно упростить

2022-01-19 07:29 UTC, VidgarVii commented on app/models/test.rb
>      .where(categories: { title: category_title })
так же благодаря ассоциациям, можно (и рекомендуется в ООП) передавать объекты для связывания по ключам, вместо аттрибутов: `category: categories[0]`, `author: users[0]` и т.п. (без `_id` , `.id`)

2022-06-07 09:57 UTC, VidgarVii requested changes

2022-06-07 09:57 UTC, VidgarVii commented on app/models/test.rb
> +  has_many :users, through: :results, dependent: :destroy
тут 1 dependent лишний. Это как раз описано в посте выше

2022-06-07 09:57 UTC, VidgarVii commented on app/models/test.rb
> +    joins(:categories)
надо перепроверить работоспособность. joins принимает название ассоциации как прописано в ассоциации.

2022-06-07 09:57 UTC, VidgarVii commented on app/models/user.rb
> +  has_many :tests, through: :results, dependent: :destroy
не исправлено

2022-06-07 09:57 UTC, VidgarVii commented on app/models/user.rb
> +    .joins(:tests)
1 метод будет возвращать не то что было указано в ТЗ. Должны быть тесты, а не результат.
2 Обрати внимание на методы ассоциации. По вызывай каждый в консоле

2022-06-10 05:05 UTC, VidgarVii commented on app/models/user.rb
> +    .where(level: level)
у тебя есть ассоциия которая возвращает все пройденные тесты
```ruby
tests.where(level: level)
```

2022-06-10 17:39 UTC, merged

2022-06-10 17:40 UTC, Lana-243 commented
added associations